### ISSUE TITLE
win11 23H2运行不正常

### ISSUE THREAD

**Issue by gzxiexl** [qq77522980/syncLazybones#1]
系统是11 23H2 系统更新到最新
安装后软件会打开控制页面 http://127.0.0.1:8384/ 
![image](https://github.com/qq77522980/syncLazybones/assets/40417977/9e595212-1e74-4ee1-8b2c-7c65f92d3af2)
但是任务管理器里又跑了syncthing 奇怪了
![image](https://github.com/qq77522980/syncLazybones/assets/40417977/7aec1339-9ca8-499e-a9ab-c2089d9f8d61)

**Comment by qq77522980** [comment]
系统版本太新了，我没这么新的系统，不过我猜测可能是syncthing版本不兼容，你可以试试把最新版syncthing覆盖到程序里面，然后再试试。

**Comment by gzxiexl** [comment]
我直接运行syncthing 又没有问题 奇怪🤔

**Comment by gzxiexl** [comment]
我用内网其他syncthing服务添加远程设备 可以判断确实启动了syncthing实例 可能是8384端口被其他程序占用了  
可是要怎么排查在哪个端口呢

**Comment by gzxiexl** [comment]
我找到原因了 我原来跑的是SyncTrayzor 他的syncthing路径和配置文件就是跟他一个路径下的
